### ISSUE TITLE
mingus?

### ISSUE THREAD

**Issue by BonifacioCalindoro** [chnihy/melodicpatternmaker#1]
Hello! I like a lot your program, congratulations! I was looking to do something like this so i will probably start from your code. But i've got a suggestion after reading the scales part: do you know mingus library? it's got like  A LOT of scales in it, and i think it's made to work with lilypond too, so maybe you could check that out before implementing more scales to you program, you'll probably save a lot of time with mingus (you won't have to write every possible scale for every key)

**Comment by chnihy** [comment]
Hi @BonifacioCalindoro - Thanks for the great idea! I use the mingus package in [RandomChordsApp](https://github.com/chnihy/randomchordsapp)

I actually built a better [scales.py](https://github.com/chnihy/scales) module a little while back, I just haven't integrated it yet.  I'm going to push a much needed update to almost everything very soon!  

In the meantime, it looks like you could very easily use mingus.core.scales to get whichever scales you want

scales.__dict__ shows me the following available scales from mingus right now:
- Diatonic
- Ionian
- Dorian
- Phrygian
- Lydian
- Mixolydian
- Aeolian
- Locrian
- Major
- HarmonicMajor
- NaturalMinor
- HarmonicMinor
- MelodicMinor
- Bachian
- MinorNeapolitan
- Chromatic
- WholeTone
- Octatonic

I've been a bit sidetracked with PyQt, MuseScore and C++ for a bit, but I should hope to have all of those scales and a generally better to read version of MPM up within the week - now that I know someone is watching lol.  
Thanks again!

**Comment by chnihy** [comment]
I'll be merging this refactored update to the main branch over this weekend (hopefully) - It's a lot more organized!
https://github.com/chnihy/melodicpatternmaker/tree/refactor_update
